library(shiny)

ui <- (pageWithSidebar( 
        headerPanel("FM synthesis visualization"),
        sidebarPanel(h3("Function parameters"),
                     h4("Oscillator 1:"),
                     radioButtons("type1", "Type:",
                                  c("Sin" = 0,
                                    "Cos" = 1)),
                     sliderInput(inputId = "freq1",
                                 label = "Frequency:",
                                 value = 1, min = 0, max = 8, step = 0.5),
                     selectInput("offset1", "Phase:", c("0" = 0,
                                                        "1/8" = 0.125,
                                                        "1/4" = 0.25,
                                                        "3/8" = 0.375,
                                                        "1/2" = 0.5,
                                                        "5/8" = 0.625,
                                                        "3/4" = 0.75,
                                                        "7/8" = 0.875,
                                                        "1" = 1)),
                     checkboxInput("amp1", "Amplification (50%)", FALSE),
                     p(" "),
                     h4("Oscillator 2:"),
                     radioButtons("type2", "Type:",
                                  c("Sin" = 0,
                                    "Cos" = 1)),
                     sliderInput(inputId = "freq2",
                                 label = "Frequency:",
                                 value = 0, min = 0, max = 8, step = 0.5),
                     selectInput("offset2", "Phase:", c("0" = 0,
                                                        "1/8" = 0.125,
                                                        "1/4" = 0.25,
                                                        "3/8" = 0.375,
                                                        "1/2" = 0.5,
                                                        "5/8" = 0.625,
                                                        "3/4" = 0.75,
                                                        "7/8" = 0.875,
                                                        "1" = 1)),
                     checkboxInput("amp2", "Amplification (50%)", FALSE),
                     p(" "),
                     h4("Oscillator 3:"),
                     radioButtons("type3", "Type:",
                                  c("Sin" = 0,
                                    "Cos" = 1)),
                     sliderInput(inputId = "freq3",
                                 label = "Frequency:",
                                 value = 0, min = 0, max = 8, step = 0.5),
                     selectInput("offset3", "Phase:", c("0" = 0,
                                                        "1/8" = 0.125,
                                                        "1/4" = 0.25,
                                                        "3/8" = 0.375,
                                                        "1/2" = 0.5,
                                                        "5/8" = 0.625,
                                                        "3/4" = 0.75,
                                                        "7/8" = 0.875,
                                                        "1" = 1
                     ))
        ),
        mainPanel( 
            h4('Resulting wave representation:'),
            plotOutput('resultWave'),
            h4("Instructions:"),
            p("The application shows a representation of the resulting wave created by summing up to three simple waveforms in form of sine or cosine functions. It is a presentation of basic FM (frequency modulation) synthesis found in early synthesizers. Three functions represent analog oscillators used for creating sound. You have the option to tweak oscillators' function type, frequency and phase and observe how it changes the resulting wave."),
            p("By default only 1st oscillator is turned on. You can add other oscillators into account by moving the frequency slider or changing phase/type parameters.
              There is also an option to add a little amplification to first two oscillators which boosts amplitude of the signal by 50%."))
    ))